### ISSUE TITLE
Help Mojy to run PaHM with SCHISM

### ISSUE THREAD

**Issue by saeed-moghimi-noaa** [noaa-ocs-modeling/PaHM#10] opened 2022-09-08 14:40 UTC

**Comment by saeed-moghimi-noaa** [comment] 2022-09-08 14:41
@SorooshMani-NOAA  @pvelissariou1 
How to make sure track file is ok?

**Comment by saeed-moghimi-noaa** [comment] 2022-09-08 14:51
@mojy3995 @SorooshMani-NOAA @pvelissariou1
We need to make sure the track files are in NHC bdeck text format (based on what @pvelissariou1  and @SorooshMani-NOAA  mentioned). -Saeed

**Comment by mojy3995** [comment] 2022-09-08 14:57
@saeed-moghimi-noaa @SorooshMani-NOAA @pvelissariou1, There is a possibility of failing pyschism to create the correct ".dat" file. Soroosh can test first with the parawind/hurricane-track.dat file (already was created by using pyschism), and if it didn't work, you can re-create that by using parametric_runs/test_paramwind.py to make sure the pyschism/python code is working correctly. I also added the original text file from Sergey. I don't have any other example to check the NHC bdeck text format, but if you have, you can compare with what we have to see if there is something wrong with the original file.

**Comment by pvelissariou1** [comment] 2022-09-08 15:34
The problem is with the formatting of hurricane-track.dat. It is the format used for longitude (column 8) in the
data file. PaHM expects 3 digits for longitude that is, 124E instead of 1243E for example. I am using the format
of b-deck files supplied by NHC. In PaHM code, I read the longitude field with the format:  i3, a1; 3 digits for longitude and a character for the West/East part. I'll check again the b-deck file format and see if I can be more general in reading the fields.

**Comment by SorooshMani-NOAA** [comment] 2022-09-08 15:36
@pvelissariou1 can you please test the original track file as well? I just want to make sure it's not the PySCHISM that's reformatting it.

**Comment by mojy3995** [comment] 2022-09-08 15:37
@pvelissariou1, Thank you!! or we can change the .py code to create the readable .dat file by PAHM.

**Comment by saeed-moghimi-noaa** [comment] 2022-09-08 15:57
Mojy,
Is this the file Sergey shared that works with ADCIRC as an input file or
still need to go through ASWIP (a prep process by adcirc modeling tools)?

Takis,
The final format input to ADCIRC and SCHISM are identical, right?

Thanks,
-Saeed


______________________________________________________
Saeed Moghimi, PhD
*NOS Storm Surge Modeling
<https://nauticalcharts.noaa.gov/learn/storm-surge-modeling.html> Team Lead*
Coastal Marine Modeling Branch, Coast Survey Development Laboratory, Office
of Coast Survey at NOAA National Ocean Service.
Address: 1315 East West Hwy, Room 6607, Silver Spring, Maryland  20910

Phone: ‪(302) 827-3986

The contents of this message are mine personally and do not necessarily
reflect any position of NOAA.

**Comment by pvelissariou1** [comment] 2022-09-08 16:00
Yes, the final format input is identical. Still checking.

**Comment by pvelissariou1** [comment] 2022-09-08 16:07
I have modified the PaHM source code and fixed the issue. It had to do with the read format in the code. I'll update PaHM and I'll create a PR to SCHISM.

**Comment by SorooshMani-NOAA** [comment] 2022-09-08 16:30
PySCHISM doesn't really do any transformation on the format. It pretty much writes out what it reads for most fields. It just adds empty fields for missing segments of the track. It was written very similar to `adcircpy`'s version of it. In this case that `124E` field is read as string and is not reformatted at all.

**Comment by mojy3995** [comment] 2022-09-08 16:32
@SorooshMani-NOAA, thank you Soroosh for the clarification.

**Comment by pvelissariou1** [comment] 2022-09-08 17:15
I updated PaHM repo and created a PR to SCHISM repo. Joseph is to review and accept the PR. Mojgan, when Joseph merges the PR, please update your SCHISM sources. Go into your SCHISM folder and run the command: git pull

**Comment by mojy3995** [comment] 2022-09-08 17:17
Sure. Thank you. Please let me know once he accepts the PR and merges that.

**Comment by pvelissariou1** [comment] 2022-09-08 19:14
Mojgan, please refresh your schism sources and re-run your test case. Joseph has merged my PR to schism. When you are successful with your test case I'll close this issue.

**Comment by mojy3995** [comment] 2022-09-08 19:15
Ok, thanks.

**Comment by pvelissariou1** [comment] 2022-09-08 19:35
Mojgan, open file schism/src/Core/PaHM/parwind.F90 and delete lines 134 and 135:
  ! Array of info about the best track data (extension to use multiple storms)
  TYPE(BestTrackData_T), ALLOCATABLE    :: bestTrackData(:)
When I copied my changes, I left this extra statement by mistake.
Please re-compile

**Comment by mojy3995** [comment] 2022-09-08 19:35
ok

**Comment by pvelissariou1** [comment] 2022-09-08 19:41
Ok, thanks. I will close this issue.

**Closed by pvelissariou1** 2022-09-08 19:41 UTC

**Comment by mojy3995** [comment] 2022-09-08 19:43
Are you going to fix that issue or I should document that?

**Comment by pvelissariou1** [comment] 2022-09-08 19:45
I created another PR to SCHISM. Issue is fixed. No need to do anything.

Panagiotis Velissariou, Ph.D., P.E.
UCAR Scientist
National Ocean and Atmospheric Administration
National Ocean Service
Office of Coast Survey CSDL/CMMB
Project Lead - Coastal Coupling
cell: (205) 227-9141
email: ***@***.***

**Comment by mojy3995** [comment] 2022-09-09 15:54
@pvelissariou1 @SorooshMani-NOAA @saeed-moghimi-noaa 
I am just checking the results and I am not sure about the accuracy of that.
This is maximum elevation: 6.551453e-06 & maximum horizontalVelX= 0.0001021061
